{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.redis -}}
--- # --------------------------------------------------------------------------------- Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd.fullname" . }}-redis-auth
  labels:
    app.kubernetes.io/component: redis
    {{- include "argocd.defaultLabels" . | nindent 4 }}
    {{- include "argocd.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $main.labels 
                          $v.labels ) ) | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
    {{- include "argocd.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $main.annotations 
                          $v.annotations ) ) | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ (randAlphaNum 32) | b64enc | quote }}